-- MySQL Script generated by MySQL Workbench
-- Tue Sep  6 13:17:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `baseDatosMeetOut` ;

-- -----------------------------------------------------
-- Schema baseDatosMeetOut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseDatosMeetOut` ;
USE `baseDatosMeetOut` ;

-- -----------------------------------------------------
-- Table `baseDatosMeetOut`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseDatosMeetOut`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `baseDatosMeetOut`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(12) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `contraseñaUsuario` VARCHAR(45) NOT NULL,
  `fotoUsuario` VARCHAR(155) NULL,
  `descripcionUsuario` VARCHAR(155) NULL DEFAULT 'Aún no he puesto descripción',
  `nombrePersona` VARCHAR(45) NULL,
  `apellidoPersona` VARCHAR(45) NULL,
  `estado` VARCHAR(9) NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`idUsuario`));



-- -----------------------------------------------------
-- Table `baseDatosMeetOut`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseDatosMeetOut`.`Eventos` ;

CREATE TABLE IF NOT EXISTS `baseDatosMeetOut`.`Eventos` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `descripcionEvento` VARCHAR(155) NOT NULL,
  `localizaciónEvento` VARCHAR(155) NOT NULL,
  `personasMax` INT NOT NULL,
  `fechaEvento` DATETIME NULL,
  PRIMARY KEY (`idEvento`));



-- -----------------------------------------------------
-- Table `baseDatosMeetOut`.`Usuarios_has_Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseDatosMeetOut`.`Usuarios_has_Eventos` ;

CREATE TABLE IF NOT EXISTS `baseDatosMeetOut`.`Usuarios_has_Eventos` (
  `Usuarios_idUsuario` INT NOT NULL,
  `Eventos_idEvento` INT NOT NULL,
  PRIMARY KEY (`Usuarios_idUsuario`, `Eventos_idEvento`),
  CONSTRAINT `fk_Usuarios_has_Eventos_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `baseDatosMeetOut`.`Usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuarios_has_Eventos_Eventos1`
    FOREIGN KEY (`Eventos_idEvento`)
    REFERENCES `baseDatosMeetOut`.`Eventos` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);




